version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Pull docker image"
          command: docker pull returntocorp/sgrep:develop
      - run:
          name: "Run sgrep"
          command: docker run --rm -v "${PWD}:/home/repo" returntocorp/sgrep:develop --config=https://sgrep.live/c/r/r2c.python
